# Generated by Django 6.0.1 on 2026-03-18 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('lab_mgmt', '0001_initial'),
        ('library_mgmt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='linked_book',
            field=models.ForeignKey(blank=True, help_text='Link to existing Book (for type=book)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='library_mgmt.book'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='linked_equipment',
            field=models.ForeignKey(blank=True, help_text='Link to existing Equipment (for type=equipment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='lab_mgmt.equipment'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='po_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_items', to='inventory.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='goods_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.goodsreturn'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='po_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='inventory.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.commodity'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier'),
        ),
    ]
