# Generated by Django 6.0.3 on 2026-03-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_busstaff_name_alter_busstaff_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpickup',
            old_name='dropped_at',
            new_name='drop_time',
        ),
        migrations.RenameField(
            model_name='studentpickup',
            old_name='picked_at',
            new_name='pickup_time',
        ),
        migrations.AddField(
            model_name='studentpickup',
            name='drop_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentpickup',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
